### ISSUE TITLE
demo错误

### ISSUE THREAD

**Issue by vapour** [toajs/toa-net#1]
原来的代码：
`const server = new net.Server(function (socket) {
  socket.on('message', (message) => {
    console.log(message)
    // { payload: { jsonrpc: '2.0', method: 'hello', params: [ 1 ] },
    //   type: 'notification' }

```
if (message.type === 'request') {
  // echo request
  socket.success(message.payload.id, message.payload.params)
}
```

  })
}).listen(8000)`

应该修改成
`const server = new net.Server(function (socket) {
  socket.on('message', (message) => {
    console.log(message)
    // { payload: { jsonrpc: '2.0', method: 'hello', params: [ 1 ] },
    //   type: 'notification' }
    // ...

```
if (message.type === 'request') {
  // echo request
  socket.success(message.payload.id, message.payload.params)
}
```

  })
});
server.listen(8000)`
否则返回的server就是net.createServer的实例，导致获取不到正确的getAuthenticator，导致不能使用auth认证

**Comment by zensh** [comment]
的确，谢谢
